#ifndef WE_ARE_CHARLIE_KIRK_INSPIRED_H
#define WE_ARE_CHARLIE_KIRK_INSPIRED_H

#include "buzzer/buzzer.h"

static buzzer_musical_note_t we_are_charlie_kirk_inspired_notes[] = {
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_CROTCHET},

    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_CROTCHET},

    {BUZZER_NOTE_REST, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_Cs, 5, BUZZER_NTYPE_CROTCHET},

    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_CROTCHET_DOTTED},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_SEMIQUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_MINIM},

    {BUZZER_NOTE_REST, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_CROTCHET},

    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_CROTCHET},

    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_MINIM},

    {BUZZER_NOTE_REST, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_Cs, 5, BUZZER_NTYPE_CROTCHET},

    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_QUAVER},

    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_B, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_A, 4, BUZZER_NTYPE_QUAVER},
    {BUZZER_NOTE_G, 4, BUZZER_NTYPE_CROTCHET},
    {BUZZER_NOTE_E, 4, BUZZER_NTYPE_MINIM_DOTTED},
};

static buzzer_melody_t we_are_charlie_kirk_inspired_melody = {
    .melody = we_are_charlie_kirk_inspired_notes,
    .length = sizeof(we_are_charlie_kirk_inspired_notes) / sizeof(we_are_charlie_kirk_inspired_notes[0]),
};

#endif